[NCL-3812] Improve Build Configuration section on Project detail page
project-ncl/pnc pull request #3374
Opened 2020-10-29 15:07 UTC by jomrazek

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2020-10-29 15:11 UTC, jomrazek commented
@matedo1 Can you look at it if I'm missing something please? Looks like it's working when I'm testing it

2020-10-30 11:28 UTC, matedo1 requested changes
Thanks for raising this fix! There are just minor comments, otherwise it looks good!

2020-10-30 11:28 UTC, matedo1 commented on ui/app/projects/detail/pnc-project-detail-page.html
> +  <pnc-build-configs-data-table page="$ctrl.buildConfigs" on-remove="null" refresh-build-configs="$ctrl.refreshBuildConfigs"></pnc-build-configs-data-table>
in this case I would also prefer to remove `refresh-build-configs="$ctrl.refreshBuildConfigs"` part as this part of the code should not be used in the future

2020-10-30 11:28 UTC, matedo1 commented on ui/app/projects/detail/pncProjectDetailPage.js
> +    function refreshBuildConfigs(buildConfigs) {
the same as above, I would prefer to remove this method

2020-10-30 19:37 UTC, matedo1 approved these changes

2020-10-30 20:01 UTC, merged