[NCL-6402] Add endpoint for build configs that include latest build
project-ncl/pnc pull request #3481
Opened 2021-03-04 11:44 UTC by dominikbrazdil

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2021-03-04 12:06 UTC, janinko requested changes

2021-03-04 12:06 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +        buildConfigurations.getContent().forEach(bc -> {
I would maybe extract the lambda to a method. This method is getting a little bit long.
probalby `BuildConfigurationWithLatest someGoodName(BuildConfiguration buildConfig)`

2021-03-04 12:08 UTC, janinko commented on rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
> +    Page<BuildConfigurationWithLatest> getAllWithLatestBuild(@Valid @BeanParam PageParameters pageParams);
Is there `@Path` annotation missing?

2021-03-04 13:57 UTC, dominikbrazdil commented on rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/BuildConfigurationEndpoint.java
> +    Page<BuildConfigurationWithLatest> getAllWithLatestBuild(@Valid @BeanParam PageParameters pageParams);
Yeah.. I'm stupid

2021-03-11 13:08 UTC, dominikbrazdil commented
retest this please

2021-03-22 18:25 UTC, janinko approved these changes

2021-03-23 10:11 UTC, merged