[NCL-6402] Cut off unnecessary data from endpoint response
project-ncl/pnc pull request #3501
Opened 2021-04-27 14:04 UTC by dominikbrazdil

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2021-05-13 10:03 UTC, janinko requested changes

2021-05-13 10:03 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                .min(Comparator.comparing(BuildTask::getSubmitTime));
why min?

2021-05-13 10:22 UTC, dominikbrazdil commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +            return null;
Right, should I return an empty List, or what would be good practice?

2021-05-13 10:24 UTC, dominikbrazdil commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                .min(Comparator.comparing(BuildTask::getSubmitTime));
there should be max I believe

2021-05-13 11:08 UTC, dominikbrazdil commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                        : latestBuildRecord.map(buildRecord -> buildMapper.toDTO(buildRecord)).orElse(null));
This won't compile, I can do
`Optional<Build> latestBuild = Optional.ofNullable(latestBuildTask.map(buildMapper::fromBuildTask)
        .orElse(latestBuildRecord.map(buildMapper::toDTO).orElse(null)));`

2021-05-13 11:25 UTC, dominikbrazdil commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +                BuildRecord.class);
This should work, we just could not come up with JPQL version fo the query (we had some struggles with inner select) but this seems to work :) thanks, will integrate this

2021-05-13 12:08 UTC, dominikbrazdil commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +                BuildRecord.class);
Could not this query give wrong results when there were more BRs with identical submitTime but connected to different BC in ?1?

2021-05-13 13:09 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                        : latestBuildRecord.map(buildRecord -> buildMapper.toDTO(buildRecord)).orElse(null));
I didn't realize that `latestBuild` is Optional. Is there reson for it to be Optional? I think you use it only with `.orElse(null)`

2021-05-13 13:11 UTC, janinko commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +            return null;
I would say throw an exception

2021-05-13 13:16 UTC, janinko commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +                BuildRecord.class);
I hope it will not, but I just copied most of it from Stack Overflow :D 
Can you try it with enabled hibernate logging of the querries (see comments in integration-test/pom.xml) to see what it actually uses?

2021-05-13 13:20 UTC, dominikbrazdil commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/BuildRecordRepositoryImpl.java
> +            return null;
Ok, now it's removed anyway. JPQL probably issues this by itself

2021-05-13 13:21 UTC, dominikbrazdil commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                        : latestBuildRecord.map(buildRecord -> buildMapper.toDTO(buildRecord)).orElse(null));
Yeah I just wanted to be clear that the latestBuild does not have to be there at all

2021-05-13 14:27 UTC, dominikbrazdil commented
retest this please

2021-05-17 07:56 UTC, janinko approved these changes

2021-05-17 07:56 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                .filter(br -> br.getBuildConfigurationId().equals(mapper.getIdMapper().toEntity(buildConfig.getId())))
I would extract `mapper.getIdMapper().toEntity(buildConfig.getId())` to variable as it's lenghty and used twice in this method.

2021-05-17 07:56 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/providers/BuildConfigurationProviderImpl.java
> +                .latestBuildUsername(latestBuild == null ? "" : latestBuild.getUser().getUsername())
before you passed null when there was no build, now you pass empty string. Not sure which one is better.

2021-05-17 08:52 UTC, merged