[NCL-6838] Add validation that brew name is available when pushing buid
project-ncl/pnc pull request #3578
Opened 2022-01-18 17:52 UTC by janinko

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2022-01-25 19:09 UTC, janinko commented on bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
> +        if (executionRootName == null){
I did it like this beacause I don't care about what `genericParameters` contains or not, I care whether `executionRootName` is null or not. I updated it though

2022-01-27 08:21 UTC, michalovjan requested changes

2022-01-27 08:21 UTC, michalovjan commented on bpm/src/main/java/org/jboss/pnc/bpm/causeway/BuildResultPushManager.java
> +            if (genericParameters.containsKey(BREW_BUILD_NAME)) {
```suggestion
            if (genericParameters.containsKey(BREW_BUILD_NAME)) {
```
```suggestion
            if (genericParameters.containsKey(BREW_BUILD_NAME.name())) {
```

2022-01-27 09:30 UTC, michalovjan approved these changes

2022-01-27 09:31 UTC, merged