[NCL-7076] - remove old BPM invocation code.
project-ncl/pnc pull request #3638
Opened 2022-10-17 12:14 UTC by matejonnet

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2022-10-20 12:02 UTC, michalovjan requested changes

2022-10-20 12:02 UTC, michalovjan commented on facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
> +    private AtomicInteger nextTaskId = new AtomicInteger(1);
I don't think we need it. TaskIds were the way how to identify tasks in memory and Maitai AFAIK.

2022-10-20 12:02 UTC, michalovjan commented on facade/src/main/java/org/jboss/pnc/facade/providers/SCMRepositoryProviderImpl.java
> +        task.setTaskId(nextTaskId.getAndIncrement()); // TODO why do we need this ID
I don't think it's needed. Is it used in RHPAM?

2022-10-20 12:04 UTC, matejonnet commented on bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
>      private Integer taskId;
Yes, only in one case, in the notifications of Repository Creation. I wanted to remove it but it's out of the scope for this task.

2022-10-26 12:14 UTC, matejonnet commented on bpm/src/main/java/org/jboss/pnc/bpm/ConnectorFactory.java
> +public class ConnectorFactory {
Removed the factory.

2022-10-31 12:01 UTC, michalovjan commented on bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
>      private Integer taskId;
Can we create a JIRA ticket for it then?

2022-10-31 12:11 UTC, michalovjan requested changes
Conflict, otherwise I LIKE IT!

2022-11-02 08:07 UTC, matejonnet commented on bpm/src/main/java/org/jboss/pnc/bpm/BpmTask.java
>      private Integer taskId;
NCL-7407

2022-11-02 08:51 UTC, merged