[NCL-7337] OTEL instrumentation of PNC Orchestrator
project-ncl/pnc pull request #3647
Opened 2022-10-26 20:32 UTC by vibe13

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

2022-10-27 08:33 UTC, matejonnet requested changes

2022-10-27 08:33 UTC, matejonnet commented on common/src/main/java/org/jboss/pnc/common/logging/MDCUtils.java
>          return mappings;
See pnc-common:MDCUtils (added recently)

2022-10-27 08:33 UTC, matejonnet commented on rest/src/main/java/org/jboss/pnc/rest/RequestLoggingFilter.java
> +        String traceId = requestContext.getHeaderString("trace-id");
Why not using pnc-api://MDCHeaderKeys

2022-10-28 12:38 UTC, merged

2022-10-28 12:39 UTC, vibe13 commented
@matejonnet I have fixed your comments and merged