[NCL-7640] Add support for upgrade paths for deprecated environments
project-ncl/pnc pull request #3680
Opened 2023-03-16 12:33 UTC by janinko

Add new endpoint to deprecate environments
Set DEPRECATION_UPGRADE attribute when an environment is being deprecated.

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/pnc/wiki/Changelog) for your change if user-facing?
* [x] Have you added unit tests for your change?

2023-03-16 12:34 UTC, janinko commented
Requires https://github.com/project-ncl/pnc-api/pull/138 to be merged

2023-03-16 13:45 UTC, pkocandr commented on facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
> +        return storedEntity;
I'm missing one thing here. When we deprecate an older version of an env which was an upgrade target for another deprecated env, should we update also the DEPRECATION_UPGRADE value which pointed to the currently deprecated environment to point at the new one? That way we would return the upgrade target right away and save the user from having to walk through the deprecated path iteratively.

2023-03-16 13:47 UTC, pkocandr commented on facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
> +        return storedEntity;
Or maybe not here, but in the deprecateActiveEnvironmentsWithSameName().

2023-03-16 15:15 UTC, pkocandr requested changes
I believe the updated envs need to be saved explicitely. The unused imports are just a cherry on top :-)

2023-03-16 15:15 UTC, pkocandr commented on spi/src/main/java/org/jboss/pnc/spi/datastore/predicates/EnvironmentPredicates.java
> +import java.util.Map;
Another unused import.

2023-03-17 21:05 UTC, pkocandr commented on facade/src/main/java/org/jboss/pnc/facade/providers/EnvironmentProviderImpl.java
> +            environment.putAttribute(Attributes.DEPRECATION_REPLACEMENT, replacementId);
OK.

2023-03-17 21:06 UTC, pkocandr approved these changes

2023-03-20 13:58 UTC, merged