Move coordination test to it
project-ncl/pnc pull request #3748
Opened 2023-06-22 13:45 UTC by matejonnet

### Checklist:

* [ ] Have you added unit tests for your change?

2023-06-26 10:53 UTC, matejonnet commented
Re-test this please!

2023-06-26 11:19 UTC, matejonnet commented
Re-test this please!

2023-07-04 15:09 UTC, michalovjan requested changes
Tests are cool. It's mostly cleanup and structuring of the tests.

2023-07-04 15:09 UTC, michalovjan commented on integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/RemoteServices.java
Can the GenericContainer of rexContainer be extracted into seperate class?

2023-07-05 10:10 UTC, matejonnet commented on integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/BuildTest.java
> +    WebSocketClient wsClient = new VertxWebSocketClient();
Because it is closest to the old tests.

2023-07-05 10:12 UTC, matejonnet commented on integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/RemoteServices.java
It can, but since all the tests extend RemoteServices, I don't see any real value in doing it.

2023-07-10 19:58 UTC, matejonnet commented on integration-test-rex/src/test/java/org/jboss/pnc/integrationrex/DependentBuildsTest.java
> +    public static class BPMWireMock implements Closeable {
Extracted common bits, but not moved as an option to add an instance of extension is required.

2023-07-10 19:59 UTC, matejonnet commented
Re-test this please!

2023-07-10 23:10 UTC, merged