[NCL-7074] Remove build log pasing from BPM
project-ncl/pnc pull request #3758
Opened 2023-06-28 16:46 UTC by janinko

### Checklist:

* [ ] Have you added unit tests for your change?

2023-06-29 11:06 UTC, matejonnet requested changes

2023-06-29 11:06 UTC, matejonnet commented on build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/DatastoreAdapterTest.java
>          Assert.assertTrue(buildRecord.getBuildLog().contains(REPOSITORY_MANAGER_LOG));
Why did you leave this in ?

2023-06-29 15:27 UTC, janinko commented
retest this please

2023-07-10 12:59 UTC, janinko commented on build-coordinator/src/test/java/org/jboss/pnc/coordinator/test/DatastoreAdapterTest.java
>          Assert.assertTrue(buildRecord.getBuildLog().contains(REPOSITORY_MANAGER_LOG));
Removed

2024-03-26 17:42 UTC, janinko commented
This was done in https://github.com/project-ncl/pnc/pull/3987

2024-03-26 17:42 UTC, closed without merging