[NCL-7279] Stop logging cancelled builds as ERROR
project-ncl/pnc pull request #3805
Opened 2023-09-04 10:17 UTC by nikitabugrovsky

Do not report cancelled builds as ERROR in userLog.

2023-09-06 14:31 UTC, michalovjan requested changes

2023-09-06 14:31 UTC, michalovjan commented on remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
> +                    message = "Build failed.";
FAILED for emphasis.

2023-09-06 20:40 UTC, thescouser89 commented
retest this please

2023-09-07 12:27 UTC, nikitabugrovsky commented on remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
> +        if (getBuildStatus(buildResult) != null) {
done!

2023-09-07 12:28 UTC, nikitabugrovsky commented on remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
> +                    message = "Build failed.";
done!

2023-09-07 12:28 UTC, nikitabugrovsky commented on remote-build-coordinator/src/main/java/org/jboss/pnc/remotecoordinator/builder/datastore/DatastoreAdapter.java
> +                    message = "Build cancelled.";
done!

2023-09-07 12:29 UTC, nikitabugrovsky commented
retest this please

2023-09-07 12:49 UTC, michalovjan approved these changes

2023-09-07 12:49 UTC, merged