[NCLSUP-990] -  Do not create duplicated artifacts after DelAnalyzer analysis
project-ncl/pnc pull request #3876
Opened 2023-11-08 13:26 UTC by vibe13

### Checklist:

* [ ] Have you added unit tests for your change?

2023-11-08 14:44 UTC, janinko requested changes

2023-11-08 14:44 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
> +            return Optional.of(artifacts.iterator().next());
If you want it shorter :smile: 
```suggestion
            return artifacts.stream().findFirst();
```

2023-11-08 14:44 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
> +                        .orElse(artifacts.iterator().next()));
What is this supposed to do? `artifacts` is not empty, so findFirst should always be present Optional.

2023-11-08 14:44 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
> +    private static int getArtifactQuality(Object obj) {
```suggestion
    private static int getNotFoundArtifactRating(org.jboss.pnc.model.Artifact artifact) {
```

2023-11-08 15:32 UTC, vibe13 commented
Thanks for the review and improvements @janinko ! I will wait for https://github.com/project-ncl/pnc/pull/3875 to land first. In the meantime I will make the same changes in https://github.com/project-ncl/pnc/pull/3864. Thanks!

2023-11-09 11:18 UTC, vibe13 commented
retest this please

2023-11-09 13:01 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
> +                .findFirst();
Looking at this, the special case for size 1 is not technically necessary. But maybe it's more understandable like this?

2023-11-09 13:01 UTC, janinko commented on facade/src/main/java/org/jboss/pnc/facade/deliverables/DeliverableAnalyzerManagerImpl.java
> +    private static int getNotFoundArtifactRating(Object obj) {
Why the method can't take Artifact?

2023-11-27 09:46 UTC, closed without merging