[NCL-7815] Implement Product Milestone Comparison REST API
project-ncl/pnc pull request #4138
Opened 2024-12-11 13:01 UTC by patrikk0123

### Checklist:

* [ ] Have you added unit tests for your change?

2025-01-06 10:25 UTC, michalovjan requested changes

2025-01-06 10:25 UTC, michalovjan commented on rest-api/src/main/java/org/jboss/pnc/rest/api/swagger/response/SwaggerPages.java
> +    public static class DeliveredArtifactInMilestonesPage extends Page<DeliveredArtifactInMilestones> {
not used

2025-01-06 10:25 UTC, michalovjan commented on spi/src/main/java/org/jboss/pnc/spi/datastore/repositories/ProductMilestoneRepository.java
> +    List<Tuple> getArtifactsDeliveredInMilestones(List<Integer> milestoneIds);
Describe what's in the tuple and the query you're making. From interface standpoint this looks extremely generic and there's little indication what's happening unless you dig into implementation since this is not the simplest of queries.

2025-01-06 10:47 UTC, michalovjan requested changes

2025-01-08 14:05 UTC, patrikk0123 commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
> +        Predicate isMavenOrNpmArtifact = cb.or(
yours is more concise so I went with that

2025-01-08 14:12 UTC, patrikk0123 commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
> +        query.groupBy(
bacause of SimpleCase, i need to group by Milestone ID, and consequently by all those other columns (otherwise SQL builder fails)

2025-01-08 14:29 UTC, patrikk0123 commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
> +            simpleCase.when(milestoneId, 1);
It can be boolean I think

2025-01-08 14:56 UTC, patrikk0123 commented on dto/src/main/java/org/jboss/pnc/dto/response/ArtifactVersion.java
> +    protected final String artifactVersion;
idk wdym by this

2025-01-08 15:06 UTC, patrikk0123 commented on integration-test/src/test/java/org/jboss/pnc/integration/endpoints/ProductMilestoneEndpointTest.java
> +                .artifactIdentifierPrefix("demo:built-artifact16")
we decided that prefix should be only group/artifact ID or name; without any version

2025-01-08 15:16 UTC, patrikk0123 commented on facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
> +        List<Integer> milestoneIntIds = milestoneIds.stream().map(Integer::valueOf).collect(Collectors.toList());
I converted input dto to `List<Integer>`, but maybe its weird from REST POV, becauase Milestone DTO has ID of String type

2025-01-08 15:30 UTC, patrikk0123 commented on rest-api/src/main/java/org/jboss/pnc/rest/api/endpoints/ProductMilestoneEndpoint.java
> +    @POST
I converted it into GET method

2025-01-08 15:31 UTC, patrikk0123 commented
@michalovjan can u take a look again, please?

2025-01-13 23:27 UTC, michalovjan commented on common/pom.xml
> -  <modelVersion>4.0.0</modelVersion>
Oh okay, then there must be settings for indentation in the ide. Could you keep 2 spaces? IMO better readability.

2025-01-14 14:54 UTC, patrikk0123 commented on facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
> +        List<Integer> milestoneIntIds = milestoneIds.stream().map(Integer::valueOf).collect(Collectors.toList());
Will be handled in another Jira, along with validation of other String DTO ID -> Integer Model ID conversions.

2025-01-14 16:19 UTC, patrikk0123 commented on facade/src/main/java/org/jboss/pnc/facade/providers/ProductMilestoneProviderImpl.java
> +            return milestonePresence == 1;
added test for no common artifact prefix delivered in milestones.
should handle both these checks:
```java
.filter(milestoneId -> {
  Boolean milestonePresence = tuple.get(3 + milestoneIds.indexOf(milestoneId), Boolean.class);
  return milestonePresence.booleanValue();
}) // artifact was delivered in the particular milestone

.filter(entry -> entry.getValue().size() >= ARTIFACT_PREFIX_SHARED_IN_MIN_MILESTONES_COUNT) // prefix delivered in at least 2 milestones
```

2025-01-14 16:27 UTC, patrikk0123 commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
> +        Predicate notFromScratchAnalysis = cb
i needed the same predicate here:
https://github.com/project-ncl/pnc/pull/4141/files#diff-37fdf2be118f8c59981d031c3a0a8ad5f57f774576e93f191533c29b9aa8f1ebR556

any idea where to extract it? there are some predicate classes but follow different structure than this predicate

2025-01-15 14:27 UTC, michalovjan commented on datastore/src/main/java/org/jboss/pnc/datastore/repositories/ProductMilestoneRepositoryImpl.java
> +        Predicate notFromScratchAnalysis = cb
I'd add it to predicate class or create the predicate if it's missing. Doesn't matter that this is more generic but the class name categorizes where the predicate belongs.

2025-01-15 14:27 UTC, michalovjan approved these changes

2025-01-20 11:36 UTC, merged